### PR TITLE
Update to .net 4.5 and migrate to Umbraco 7.6

### PR DESCRIPTION
**Pull request by xumix**
See #146

### CODE REVIEW

**Comment by skttl** [comment]
Hi @xumix 

I tried using a custom build, with your pull request in it. But can't save any redirects. Does it work for you?

**Comment by xumix** [comment]
@skttl I'll try it myself. Btw, could you help and fix the error?

**Comment by skttl** [comment]
No, I ended up migrating my redirects to another package.

**Comment by xumix** [comment]
@skttl How did you managed this? What package have I migrated to?
I'm thinking of the same

**Comment by skttl** [comment]
This one: https://github.com/skybrud/Skybrud.Umbraco.Redirects

I have a gist for migration here: https://gist.github.com/skttl/a1ad852ea094e8dd4a7c80d87fefb857

Note, there is no 404 tracking in this package

**Comment by xumix** [comment]
@skttl Thanks!

**Pull request closed without merging**
