### PR TITLE
Added sql query caching to reduce calls to db

### PR DESCRIPTION
**Pull request by tgriley**

### CODE REVIEW

**Comment by tgriley** [comment]
Damn, looks like my vs settings have normalized code formatting on all files I edited making diffs impossible. Sorry :S

**Comment by kipusoep** [comment]
Yeah, that kind of sucks :-p
Can't you use normal indenting ;-) and re-do the PR?

**Comment by tgriley** [comment]
Just changed white space to tabs, hasn't made much difference as other auto formatting guff has also been performed sorry.

**Comment by kipusoep** [comment]
Okay, no problem.

The only thing I'm concerned about is that this is quite a big PR and I've had a big PR before, which didn't work out the way it should have.
That big PR introduced relatively massive bugs and some are sitll unsolved. If you take a look at the big list of issues at the moment, you know what I'm talking about.

How do we know everything works fine and no bugs are introduced, how well have you tested it?

**Comment by tgriley** [comment]
We have dedicated test resource so its been tested twice, once by me and again by them and had performance tests ran against it (made a huge difference with our setup :D ). its been deployed to a test environment and is on its way into production as we speak for 2 large(ish) websites. 
However I cant expect you to just take my word for it! I'll try to have a look at making the changes clearer out of work hours so you can judge for yourself. Can't promise when that'll be though if I'm honest. Hopefully ill get some time over the weekend.

**Comment by tgriley** [comment]
Although... it says it cal all auto merge fine, could you accept it and diff the results of the merge?

**Comment by kipusoep** [comment]
Accepted, but don't know how to get a diff of the results?

**Comment by tgriley** [comment]
if you pull locally and diff with each of those formatted files separately with the version before my changes it should give you a much nicer picture. Especially if you use kdiff or something which can ignore white space differences?

**Comment by tgriley** [comment]
Shortly there will be another piece of work against this project to make it install via nuget so we can upgrade it as per our current CI process. Ill send that your way once we're happy with it too.

**Comment by kipusoep** [comment]
But it already installs via nuget?

**Comment by tgriley** [comment]
Oh right! Awesome lol. Don't know how I missed that :-S

**Comment by kipusoep** [comment]
Btw, I've moved some new classes to folder/namespaces with commit 2bf656db054910b532fafbadf9068cbc072235db.

**Comment by tgriley** [comment]
Yeeee they where a little out of place at root :-). Have you had a chance
to test/benchmark yet?

**Comment by kipusoep** [comment]
Merging and testing it at the moment. Also trying to look into the many issues that have been reported, but in the past I've been unable to reproduce them :-/

**Comment by tgriley** [comment]
Must be a nightmare maintaining a package so widely used!

**Comment by kipusoep** [comment]
It has been lately, because I can't keep up to the expectations :-(
Before it felt great, because it was a killer package doing it's job. Now features have been added which degrade performance (which you've hopefully fixed ;-) ) or introduce bugs (PR from some time ago with multi-site improvements).
I'm still trying to get the UrlTracker stable again, it's a pain in the ass, especially when you're unable to reproduce this many issues...

So thanks for your help, greatly appreciated :-)

**Comment by kipusoep** [comment]
Houston, I think we have a problem :-P

image

**Comment by kipusoep** [comment]
This might explain:
image

**Comment by tgriley** [comment]
Hummmm, I only ran it against fully fledged SQL Server. Hummm, Seems strange as RecordReaderCache just mimics Umbraco's own RecordReader implementation essentially.

Thats not cricket.

Can you try it against a sql server db just to make sure thats the route cause?

**Comment by kipusoep** [comment]
It is, haven't tried against SQL Server yet, but that's the reason the RecordsReaderCachedEntry is null.

**Comment by tgriley** [comment]
Hows it looking?

**Comment by kipusoep** [comment]
Well, I'm afraid I'll have to undo the merge of this PR, because it breaks stuff... :-(

**Comment by tgriley** [comment]
Awh no, gutted. Is it the sql server compact malarkey stil?

**Comment by kipusoep** [comment]
Yes, I haven't changed anything.

**Comment by kipusoep** [comment]
I've managed to revert the PR. Please create a new PR when the SqlCE issue has been fixed :-)

**Pull request merged**
