### PR TITLE
Domain on child node with cross site/host redirects

### PR DESCRIPTION
**Pull request by sandromastronardi**
When there is a dual level redirect structure with a domain on the first level, and a culture on a second, then the second level wasn't available in the rootsite dropdown...
Added is now a configuration value to enable this...
it will work like this for example:
http://www.site.com/primarysite/nl
primarysite has the domain http://www.site.com/primarysite
and nl has the language added to it (counting as a domain for umbraco)

The dropdown will show primarysite/nl and primarysite/en if there are two child sites...
To prevent global redirects on http://www.site.com/redirect to be bound to the primary site, but have them work for all domains (also if sorting changes), it is now possible to bind them to the -1 root... causing it to work on every request, unless there is an override from a specific site... Hence the dropdown shows the root (/) as first item when more domains are found. Also redirects will be relative to the full domain, so it will work if the redirect 'test' is www.domain.com/test but also if the domain is configured as www.domain.com/site the redirect will be www.domain.com/site/test

A few strings where replaced by their constant alternatives (in the Uri class)

Because the multilevel sites can also have different hostnames the redirects will now also work if the redirect is to a site on another hostname, the redirect will then have the full hostname... if the redirect is to a link internal to the current site (regardles of which hostname is currently used to access the site) it will do a relative redirect to prevent redirects to always go to the primary domain...
The visualisation also shows this by showing the full Url if the redirect will be cross domain...

If there is only one domain and in the style of www.site.com/corporate (so no www.site.com alone) then the dropdown to choose root is available when editing and creating... otherwise it would not be possible to create redirects like www.site.com/redirect

### CODE REVIEW

**Comment by kipusoep** [comment]
What is https://github.com/mastrosoft/UrlTracker/blob/DomainOnChildNode/Models/axrk0021.nh2 ?

**Comment by sandromastronardi** [comment]
Goeie vraag, een backup van een cs of zo?

Van: Stefan Kip [mailto:notifications@github.com]
Verzonden: woensdag 28 januari 2015 15:17
Aan: kipusoep/UrlTracker
CC: Sandro Mastronardi - Mastronardi Software
Onderwerp: Re: [UrlTracker] Domain on child node with cross site/host redirects (#40)


What is https://github.com/mastrosoft/UrlTracker/blob/DomainOnChildNode/Models/axrk0021.nh2 ?

**Comment by kipusoep** [comment]
Geen idee, het zit in jouw PR ;-)

**Comment by sandromastronardi** [comment]
Jah, ik weet het ☺ is een rare extentie… denk dat het zo iets is, recovery of zo…

Van: Stefan Kip [mailto:notifications@github.com]
Verzonden: woensdag 28 januari 2015 15:22
Aan: kipusoep/UrlTracker
CC: Sandro Mastronardi - Mastronardi Software
Onderwerp: Re: [UrlTracker] Domain on child node with cross site/host redirects (#40)


Geen idee, het zit in jouw PR ;-)

**Comment by kipusoep** [comment]
Nog iets gevonden wat er niet thuis hoort: https://github.com/kipusoep/UrlTracker/commits/master/Extensions/InfoCaster.Umbraco.UrlTracker.dll

**Comment by sandromastronardi** [comment]
Da’s raar… is me ook niet opgevallen bij ’t maken van de PR, dan valt vooral code op natuurlijk… maar ja, ‘k snap niet hoe die daar komt eigenlijk… dacht nochtans wel dat ‘k helemaal fris begonnen was toen ‘k de code van ornella meenaam naar dit project, dus verloren gelopen dll’s zijn dan wel raar…

Sandro

Van: Stefan Kip [mailto:notifications@github.com]
Verzonden: woensdag 28 januari 2015 18:22
Aan: kipusoep/UrlTracker
CC: Sandro Mastronardi - Mastronardi Software
Onderwerp: Re: [UrlTracker] Domain on child node with cross site/host redirects (#40)


Nog iets gevonden wat er niet thuis hoort: https://github.com/kipusoep/UrlTracker/commits/master/Extensions/InfoCaster.Umbraco.UrlTracker.dll

**Comment by kipusoep** [comment]
Wilde het in ieder geval even doorgeven ;-)
Je PR zit overigens in de zojuist uitgebrachte versie 3.4 :+1: 

Thanks voor je hulp!!!

**Comment by sandromastronardi** [comment]
Ja, mag zeker ☺
Super, da’s fijn om te horen, graag gedaan

Van: Stefan Kip [mailto:notifications@github.com]
Verzonden: woensdag 28 januari 2015 18:33
Aan: kipusoep/UrlTracker
CC: Sandro Mastronardi - Mastronardi Software
Onderwerp: Re: [UrlTracker] Domain on child node with cross site/host redirects (#40)


Wilde het in ieder geval even doorgeven ;-)
Je PR zit overigens in de zojuist uitgebrachte versie 3.4 [:+1:]

Thanks voor je hulp!!!

**Pull request merged**
